preload=/home/th/Pictures/Wallpapers/911 GT3 RS racetrack.jpg
# wallpaper=DP-1,/home/th/.config/hyde/themes/Catppuccin\ Mocha/wallpapers/evening_sky.png
wallpaper {
    monitor = DP-1
    path = /home/th/Pictures/Wallpapers/911 GT3 RS racetrack.jpg
    fit_mode = cover
}
splash = false
