-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

local HYDE_HYPRLAND = "set"

--! Do not remove - HyDE marker to prevent file overwrite
--* You can freely edit this file, but make sure to not remove the above line!
--* All Files Below are yours to modify!
--!      ░▒▒▒░░░▓▓           ___________
--!    ░░▒▒▒░░░░░▓▓        //___________/
--!   ░░▒▒▒░░░░░▓▓     _   _ _    _ _____
--!   ░░▒▒░░░░░▓▓▓▓▓▓ | | | | |  | |  __/
--!    ░▒▒░░░░▓▓   ▓▓ | |_| | |_/ /| |___
--!     ░▒▒░░▓▓   ▓▓   \__  |____/ |____/
--!       ░▒▓▓   ▓▓  //____/

--? Read https://hydeproject.pages.dev/en/configuring/hyprland/ for the full documentation.

require("keybindings")

-- Keyboard shortcuts

require("windowrules")

-- Window rules

require("monitors")

-- Monitor configuration

require("userprefs")

-- Your hyprland configuration // Edit this file to change your Hyprland configuration

-- HyprEmoji config
local hypremoji_path = os.getenv("HOME") .. "/.config/hypremoji/hypremoji.lua"
if io.open(hypremoji_path) then
	dofile(hypremoji_path)
end
