-- Generated by hyprconf2lua v1.4.0, hand-repaired
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Fixed: mangled screenshot commands, dropped repeat flags, dropped descriptions

---@module 'hl'

--# █▄▀ █▀▀ █▄█ █▄▄ █ █▄░█ █▀▄ █ █▄░█ █▀▀ █▀
--# █░█ ██▄ ░█░ █▄█ █ █░▀█ █▄▀ █ █░▀█ █▄█ ▄█

-- see https://wiki.hyprland.org/configuring/keywords/ for more
-- example binds, see https://wiki.hyprland.org/configuring/binds/ for more

local mainMod = "SUPER"

hl.bind(mainMod .. " + " .. "Q", hl.dsp.window.close(), { description = "[Window Management] close focused window" })
hl.bind("ALT" .. " + " .. "F4", hl.dsp.window.close(), { description = "[Window Management] close focused window" })
hl.bind(
	mainMod .. " + " .. "Delete",
	hl.dsp.exec_cmd("hyde-shell logout"),
	{ description = "[Window Management] kill hyprland session" }
)
hl.bind(mainMod .. " + " .. "W", hl.dsp.window.float(), { description = "[Window Management] Toggle floating" })
hl.bind(mainMod .. " + " .. "G", hl.dsp.group.toggle(), { description = "[Window Management] toggle group" })
hl.bind(
	"SHIFT" .. " + " .. "F11",
	hl.dsp.window.fullscreen(),
	{ description = "[Window Management] toggle fullscreen" }
)
hl.bind(mainMod .. " + " .. "L", hl.dsp.exec_cmd("lockscreen.sh"), { description = "[Window Management] lock screen" })
hl.bind(
	mainMod .. " + SHIFT" .. " + " .. "F",
	hl.dsp.exec_cmd(hyde.sh.window.pin()),
	{ description = "[Window Management] toggle pin on focused window" }
)
hl.bind(
	"CONTROL + ALT" .. " + " .. "Delete",
	hl.dsp.exec_cmd("$HOME/.local/lib/hyde/logoutlaunch.sh"),
	{ description = "[Window Management] logout menu" }
)
hl.bind(
	"Alt_R" .. " + " .. "Control_R",
	hl.dsp.exec_cmd("hyde-shell waybar --hide"),
	{ description = "[Window Management] toggle waybar and reload config" }
)
hl.bind(
	mainMod .. " + SHIFT" .. " + " .. "R",
	hl.dsp.exec_cmd("killall waybar || waybar"),
	{ description = "[Window Management] toggle waybar" }
)
-- toggle waybar without reloading, this is faster
hl.bind(
	mainMod .. " + CONTROL" .. " + " .. "H",
	hl.dsp.group.next({ forward = false }),
	{ description = "[Window Management|Group Navigation] change active group backwards" }
)
hl.bind(
	mainMod .. " + CONTROL" .. " + " .. "L",
	hl.dsp.group.next(),
	{ description = "[Window Management|Group Navigation] change active group forwards" }
)
hl.bind(
	mainMod .. " + " .. "Left",
	hl.dsp.focus({ direction = "left" }),
	{ description = "[Window Management|Change focus] focus left" }
)
hl.bind(
	mainMod .. " + " .. "Right",
	hl.dsp.focus({ direction = "right" }),
	{ description = "[Window Management|Change focus] focus right" }
)
hl.bind(
	mainMod .. " + " .. "Up",
	hl.dsp.focus({ direction = "up" }),
	{ description = "[Window Management|Change focus] focus up" }
)
hl.bind(
	mainMod .. " + " .. "Down",
	hl.dsp.focus({ direction = "down" }),
	{ description = "[Window Management|Change focus] focus down" }
)
hl.bind(
	"ALT" .. " + " .. "Tab",
	hl.dsp.window.cycle_next(),
	{ description = "[Window Management|Change focus] Cycle focus" }
)
hl.bind("ALT + TAB", hl.dsp.window.bring_to_top())
hl.bind("ALT + SHIFT" .. " + " .. "TAB", hl.dsp.window.cycle_next({ next = false }))
hl.bind("ALT + SHIFT + TAB", hl.dsp.window.bring_to_top())
-- Resize windows
hl.bind(
	mainMod .. " + SHIFT" .. " + " .. "Right",
	hl.dsp.window.resize({ x = 30, y = 0, relative = true }),
	{ repeating = true, description = "[Window Management|Resize Active Window] resize window right" }
)
hl.bind(
	mainMod .. " + SHIFT" .. " + " .. "Left",
	hl.dsp.window.resize({ x = -30, y = 0, relative = true }),
	{ repeating = true, description = "[Window Management|Resize Active Window] resize window left" }
)
hl.bind(
	mainMod .. " + SHIFT" .. " + " .. "Up",
	hl.dsp.window.resize({ x = 0, y = -30, relative = true }),
	{ repeating = true, description = "[Window Management|Resize Active Window] resize window up" }
)
hl.bind(
	mainMod .. " + SHIFT" .. " + " .. "Down",
	hl.dsp.window.resize({ x = 0, y = 30, relative = true }),
	{ repeating = true, description = "[Window Management|Resize Active Window] resize window down" }
)
-- Move active window around current workspace with mainMod + Shift + Control [←→↑↓]
hl.bind(
	mainMod .. " + SHIFT + CONTROL" .. " + " .. "left",
	hl.dsp.exec_cmd(
		"grep -q true <<< $(hyprctl activewindow -j| jq -r.floating) && hyprctl dispatch moveactive -30 0 || hyprctl dispatch movewindow l"
	),
	{ repeating = true, description = "Move active window to the left" }
)
hl.bind(
	mainMod .. " + SHIFT + CONTROL" .. " + " .. "right",
	hl.dsp.exec_cmd(
		"grep -q true <<< $(hyprctl activewindow -j| jq -r.floating) && hyprctl dispatch moveactive 30 0 || hyprctl dispatch movewindow r"
	),
	{ repeating = true, description = "Move active window to the right" }
)
hl.bind(
	mainMod .. " + SHIFT + CONTROL" .. " + " .. "up",
	hl.dsp.exec_cmd(
		"grep -q true <<< $(hyprctl activewindow -j| jq -r.floating) && hyprctl dispatch moveactive 0 -30 || hyprctl dispatch movewindow u"
	),
	{ repeating = true, description = "Move active window up" }
)
hl.bind(
	mainMod .. " + SHIFT + CONTROL" .. " + " .. "down",
	hl.dsp.exec_cmd(
		"grep -q true <<< $(hyprctl activewindow -j| jq -r.floating) && hyprctl dispatch moveactive 0 30 || hyprctl dispatch movewindow d"
	),
	{ repeating = true, description = "Move active window down" }
)
-- Move/Resize focused window
hl.bind(
	mainMod .. " + " .. "mouse:272",
	hl.dsp.window.drag(),
	{ mouse = true, description = "[Window Management|Move & Resize with mouse] hold to move window" }
)
hl.bind(
	mainMod .. " + " .. "mouse:273",
	hl.dsp.window.resize(),
	{ mouse = true, description = "[Window Management|Move & Resize with mouse] hold to resize window" }
)
hl.bind(
	mainMod .. " + " .. "Z",
	hl.dsp.window.drag(),
	{ mouse = true, description = "[Window Management|Move & Resize with mouse] hold to move window" }
)
hl.bind(
	mainMod .. " + " .. "X",
	hl.dsp.window.resize(),
	{ mouse = true, description = "[Window Management|Move & Resize with mouse] hold to resize window" }
)
-- Toggle focused window split
hl.bind(mainMod .. " + " .. "J", hl.dsp.layout("togglesplit"), { description = "[Window Management] toggle split" })
hl.bind(mainMod .. " + " .. "T", hl.dsp.exec_cmd("kitty"), { description = "[Launcher|Apps] terminal emulator" })
hl.bind(
	mainMod .. " + ALT" .. " + " .. "T",
	hl.dsp.exec_cmd("hyde-shell pypr toggle console"),
	{ description = "[Launcher|Apps] dropdown terminal" }
)
hl.bind(mainMod .. " + " .. "E", hl.dsp.exec_cmd("dolphin"), { description = "[Launcher|Apps] file explorer" })
hl.bind(
	mainMod .. " + " .. "C",
	hl.dsp.exec_cmd(os.getenv("EDITOR") or "code"),
	{ description = "[Launcher|Apps] text editor" }
)
hl.bind(mainMod .. " + " .. "B", hl.dsp.exec_cmd("firefox"), { description = "[Launcher|Apps] web browser" })
hl.bind(mainMod .. " + " .. "M", hl.dsp.exec_cmd("spotify"), { description = "[Launcher|Apps] music player (spotify)" })
hl.bind(
	"CONTROL + SHIFT" .. " + " .. "Escape",
	hl.dsp.exec_cmd("hyde-shell system.monitor"),
	{ description = "[Launcher|Apps] system monitor" }
)
local rofi_launch = "$HOME/.local/lib/hyde/rofilaunch.sh"
-- bindd = $mainMod, Space, $d application finder , exec, pkill -x rofi || $rofi-launch d
hl.bind(
	mainMod .. " + " .. "Space",
	hl.dsp.exec_cmd("vicinae toggle"),
	{ description = "[Launcher|Rofi menus] Vicinae" }
)
hl.bind(
	mainMod .. " + " .. "TAB",
	hl.dsp.exec_cmd("pkill -x rofi || " .. rofi_launch .. " w"),
	{ description = "[Launcher|Rofi menus] window switcher" }
)
hl.bind(
	mainMod .. " + SHIFT" .. " + " .. "E",
	hl.dsp.exec_cmd("pkill -x rofi || " .. rofi_launch .. " f"),
	{ description = "[Launcher|Rofi menus] file finder" }
)
hl.bind(
	mainMod .. " + " .. "equal",
	hl.dsp.exec_cmd("rofi -show calc -modi calc -no-show-match -no-sort -calc-command \"echo -n '{result}' | wl-copy\""),
	{ description = "[Launcher|Rofi menus] calculator" }
)
hl.bind(
	mainMod .. " + " .. "slash",
	hl.dsp.exec_cmd("pkill -x rofi || $HOME/.local/lib/hyde/keybinds_hint.sh c"),
	{ description = "[Launcher|Rofi menus] keybindings hint" }
)
hl.bind(
	mainMod .. " + " .. "comma",
	hl.dsp.exec_cmd("/usr/bin/hypremoji"),
	{ description = "[Launcher|Rofi menus] emoji picker" }
)
-- bindd = $mainMod, period, $d glyph picker , exec, pkill -x rofi || $HOME/.local/lib/hyde/glyph-picker.sh # launch glyph picker
hl.bind(
	mainMod .. " + " .. "V",
	hl.dsp.exec_cmd("pkill -x rofi || $HOME/.local/lib/hyde/cliphist.sh -c"),
	{ description = "[Launcher|Rofi menus] clipboard" }
)
hl.bind(
	mainMod .. " + SHIFT" .. " + " .. "V",
	hl.dsp.exec_cmd("pkill -x rofi || $HOME/.local/lib/hyde/cliphist.sh"),
	{ description = "[Launcher|Rofi menus] clipboard manager" }
)
hl.bind(
	mainMod .. " + SHIFT" .. " + " .. "A",
	hl.dsp.exec_cmd("pkill -x rofi || $HOME/.local/lib/hyde/rofiselect.sh"),
	{ description = "[Launcher|Rofi menus] select rofi launcher" }
)
-- binddl  = , F10, $d toggle mute output , exec, ~/.config/waybar/scripts/volume.sh output mute # toggle audio mute
-- binddel = , F11, $d decrease volume , exec, ~/.config/waybar/scripts/volume.sh output lower # decrease volume
-- binddel = , F12, $d increase volume , exec, ~/.config/waybar/scripts/volume.sh output raise # increase volume
hl.bind(
	"XF86AudioMicMute",
	hl.dsp.exec_cmd("~/.config/waybar/scripts/volume.sh input mute"),
	{ locked = true, description = "[Hardware Controls|Audio] un/mute microphone" }
)
hl.bind(
	"XF86AudioMute",
	hl.dsp.exec_cmd("~/.config/waybar/scripts/volume.sh output mute"),
	{ locked = true, description = "[Hardware Controls|Audio] toggle mute output" }
)
hl.bind(
	"XF86AudioLowerVolume",
	hl.dsp.exec_cmd("~/.config/waybar/scripts/volume.sh output lower"),
	{ locked = true, repeating = true, description = "[Hardware Controls|Audio] decrease volume" }
)
hl.bind(
	"XF86AudioRaiseVolume",
	hl.dsp.exec_cmd("~/.config/waybar/scripts/volume.sh output raise"),
	{ locked = true, repeating = true, description = "[Hardware Controls|Audio] increase volume" }
)
hl.bind(
	"XF86AudioPlay",
	hl.dsp.exec_cmd("playerctl play-pause"),
	{ locked = true, description = "[Hardware Controls|Media] play media" }
)
hl.bind(
	"XF86AudioPause",
	hl.dsp.exec_cmd("playerctl play-pause"),
	{ locked = true, description = "[Hardware Controls|Media] pause media" }
)
hl.bind(
	"XF86AudioNext",
	hl.dsp.exec_cmd("playerctl next"),
	{ locked = true, description = "[Hardware Controls|Media] next media" }
)
hl.bind(
	"XF86AudioPrev",
	hl.dsp.exec_cmd("playerctl previous"),
	{ locked = true, description = "[Hardware Controls|Media] previous media" }
)
hl.bind(
	"XF86MonBrightnessUp",
	hl.dsp.exec_cmd("~/.config/waybar/scripts/brightness.sh up"),
	{ locked = true, repeating = true, description = "[Hardware Controls|Brightness] increase brightness" }
)
hl.bind(
	"XF86MonBrightnessDown",
	hl.dsp.exec_cmd("~/.config/waybar/scripts/brightness.sh down"),
	{ locked = true, repeating = true, description = "[Hardware Controls|Brightness] decrease brightness" }
)
hl.bind(
	mainMod .. " + " .. "K",
	hl.dsp.exec_cmd("$HOME/.local/lib/hyde/keyboardswitch.sh"),
	{ locked = true, description = "[Utilities] toggle keyboard layout" }
)
hl.bind(
	mainMod .. " + ALT" .. " + " .. "G",
	hl.dsp.exec_cmd("$HOME/.local/lib/hyde/gamemode.sh"),
	{ description = "[Utilities] game mode" }
)
hl.bind(
	mainMod .. " + SHIFT" .. " + " .. "G",
	hl.dsp.exec_cmd("$HOME/.local/lib/hyde/gamelauncher.sh"),
	{ description = "[Utilities] open game launcher" }
)
hl.bind(
	mainMod .. " + SHIFT" .. " + " .. "P",
	hl.dsp.exec_cmd("hyprpicker -an"),
	{ description = "[Utilities|Screen Capture] color picker" }
)
-- bindd = $mainMod, P, $d snip screen , exec, $HOME/.local/lib/hyde/screenshot.sh s # partial screenshot capture
hl.bind(
	mainMod .. " + " .. "P",
	hl.dsp.exec_cmd('grim -g "$(slurp)" - | wl-copy'),
	{ description = "[Utilities|Screen Capture] snip screen" }
)
hl.bind(
	mainMod .. " + CONTROL" .. " + " .. "P",
	hl.dsp.exec_cmd(
		"slurp | grim -g - - | tee ~/Pictures/Screenshots/$(date -Iminutes | sed 's/[-T:]//g' | cut -c-12).png | wl-copy"
	),
	{ description = "[Utilities|Screen Capture] snip screen and save to Pictures dir" }
)
hl.bind(
	mainMod .. " + ALT" .. " + " .. "P",
	hl.dsp.exec_cmd("$HOME/.local/lib/hyde/screenshot.sh m"),
	{ locked = true, description = "[Utilities|Screen Capture] print monitor" }
)
hl.bind(
	"Print",
	hl.dsp.exec_cmd("$HOME/.local/lib/hyde/screenshot.sh p"),
	{ locked = true, description = "[Utilities|Screen Capture] print all monitors" }
)
hl.bind(
	mainMod .. " + ALT" .. " + " .. "Right",
	hl.dsp.exec_cmd("$HOME/.local/lib/hyde/wallpaper.sh -Gn"),
	{ description = "[Theming and Wallpaper] next global wallpaper" }
)
hl.bind(
	mainMod .. " + ALT" .. " + " .. "Left",
	hl.dsp.exec_cmd("$HOME/.local/lib/hyde/wallpaper.sh -Gp"),
	{ description = "[Theming and Wallpaper] previous global wallpaper" }
)
hl.bind(
	mainMod .. " + SHIFT" .. " + " .. "W",
	hl.dsp.exec_cmd("pkill -x rofi || $HOME/.local/lib/hyde/wallpaper.sh -SG"),
	{ description = "[Theming and Wallpaper] select a global wallpaper" }
)
hl.bind(
	mainMod .. " + ALT" .. " + " .. "Up",
	hl.dsp.exec_cmd("hyde-shell waybar --next"),
	{ description = "[Theming and Wallpaper] next waybar layout" }
)
hl.bind(
	mainMod .. " + ALT" .. " + " .. "Down",
	hl.dsp.exec_cmd("hyde-shell waybar --prev"),
	{ description = "[Theming and Wallpaper] previous waybar layout" }
)
hl.bind(
	mainMod .. " + SHIFT" .. " + " .. "M",
	hl.dsp.exec_cmd("pkill -x rofi || $HOME/.local/lib/hyde/wallbashtoggle.sh -m"),
	{ description = "[Theming and Wallpaper] wallbash mode selector" }
)
hl.bind(
	mainMod .. " + SHIFT" .. " + " .. "T",
	hl.dsp.exec_cmd(hyde.sh.menu.themes()),
	{ description = "[Theming and Wallpaper] select a theme" }
)
hl.bind(
	mainMod .. "+SHIFT" .. " + " .. "Y",
	hl.dsp.exec_cmd("hyde-shell animations --select"),
	{ description = "[Theming and Wallpaper] select animations" }
)
hl.bind(
	mainMod .. "+SHIFT" .. " + " .. "U",
	hl.dsp.exec_cmd("pkill -x rofi || $HOME/.local/lib/hyde/hyprlock.sh --select"),
	{ description = "[Theming and Wallpaper] select hyprlock layout" }
)
hl.bind(
	mainMod .. " + " .. 1,
	hl.dsp.focus({ workspace = 1 }),
	{ description = "[Workspaces|Navigation] navigate to workspace 1" }
)
hl.bind(
	mainMod .. " + " .. 2,
	hl.dsp.focus({ workspace = 2 }),
	{ description = "[Workspaces|Navigation] navigate to workspace 2" }
)
hl.bind(
	mainMod .. " + " .. 3,
	hl.dsp.focus({ workspace = 3 }),
	{ description = "[Workspaces|Navigation] navigate to workspace 3" }
)
hl.bind(
	mainMod .. " + " .. 4,
	hl.dsp.focus({ workspace = 4 }),
	{ description = "[Workspaces|Navigation] navigate to workspace 4" }
)
hl.bind(
	mainMod .. " + " .. 5,
	hl.dsp.focus({ workspace = 5 }),
	{ description = "[Workspaces|Navigation] navigate to workspace 5" }
)
hl.bind(
	mainMod .. " + " .. 6,
	hl.dsp.focus({ workspace = 6 }),
	{ description = "[Workspaces|Navigation] navigate to workspace 6" }
)
hl.bind(
	mainMod .. " + " .. 7,
	hl.dsp.focus({ workspace = 7 }),
	{ description = "[Workspaces|Navigation] navigate to workspace 7" }
)
hl.bind(
	mainMod .. " + " .. 8,
	hl.dsp.focus({ workspace = 8 }),
	{ description = "[Workspaces|Navigation] navigate to workspace 8" }
)
hl.bind(
	mainMod .. " + " .. 9,
	hl.dsp.focus({ workspace = 9 }),
	{ description = "[Workspaces|Navigation] navigate to workspace 9" }
)
hl.bind(
	mainMod .. " + " .. 0,
	hl.dsp.focus({ workspace = 10 }),
	{ description = "[Workspaces|Navigation] navigate to workspace 10" }
)
hl.bind(
	mainMod .. " + CONTROL" .. " + " .. "Right",
	hl.dsp.focus({ workspace = "r+1" }),
	{ description = "[Workspaces|Navigation|Relative workspace] change active workspace forwards" }
)
hl.bind(
	mainMod .. " + CONTROL" .. " + " .. "Left",
	hl.dsp.focus({ workspace = "r-1" }),
	{ description = "[Workspaces|Navigation|Relative workspace] change active workspace backwards" }
)
hl.bind(
	mainMod .. " + CONTROL" .. " + " .. "Down",
	hl.dsp.focus({ workspace = "empty" }),
	{ description = "[Workspaces|Navigation] navigate to the nearest empty workspace" }
)
-- Move focused window to a workspace
hl.bind(
	mainMod .. " + SHIFT" .. " + " .. 1,
	hl.dsp.window.move({ workspace = 1 }),
	{ description = "[Workspaces|Move window to workspace] move to workspace 1" }
)
hl.bind(
	mainMod .. " + SHIFT" .. " + " .. 2,
	hl.dsp.window.move({ workspace = 2 }),
	{ description = "[Workspaces|Move window to workspace] move to workspace 2" }
)
hl.bind(
	mainMod .. " + SHIFT" .. " + " .. 3,
	hl.dsp.window.move({ workspace = 3 }),
	{ description = "[Workspaces|Move window to workspace] move to workspace 3" }
)
hl.bind(
	mainMod .. " + SHIFT" .. " + " .. 4,
	hl.dsp.window.move({ workspace = 4 }),
	{ description = "[Workspaces|Move window to workspace] move to workspace 4" }
)
hl.bind(
	mainMod .. " + SHIFT" .. " + " .. 5,
	hl.dsp.window.move({ workspace = 5 }),
	{ description = "[Workspaces|Move window to workspace] move to workspace 5" }
)
hl.bind(
	mainMod .. " + SHIFT" .. " + " .. 6,
	hl.dsp.window.move({ workspace = 6 }),
	{ description = "[Workspaces|Move window to workspace] move to workspace 6" }
)
hl.bind(
	mainMod .. " + SHIFT" .. " + " .. 7,
	hl.dsp.window.move({ workspace = 7 }),
	{ description = "[Workspaces|Move window to workspace] move to workspace 7" }
)
hl.bind(
	mainMod .. " + SHIFT" .. " + " .. 8,
	hl.dsp.window.move({ workspace = 8 }),
	{ description = "[Workspaces|Move window to workspace] move to workspace 8" }
)
hl.bind(
	mainMod .. " + SHIFT" .. " + " .. 9,
	hl.dsp.window.move({ workspace = 9 }),
	{ description = "[Workspaces|Move window to workspace] move to workspace 9" }
)
hl.bind(
	mainMod .. " + SHIFT" .. " + " .. 0,
	hl.dsp.window.move({ workspace = 10 }),
	{ description = "[Workspaces|Move window to workspace] move to workspace 10" }
)
-- Move focused window to a relative workspace
hl.bind(
	mainMod .. " + CONTROL+ALT" .. " + " .. "Right",
	hl.dsp.window.move({ workspace = "r+1" }),
	{ description = "[Workspaces] move window to next relative workspace" }
)
hl.bind(
	mainMod .. " + CONTROL+ALT" .. " + " .. "Left",
	hl.dsp.window.move({ workspace = "r-1" }),
	{ description = "[Workspaces] move window to previous relative workspace" }
)
-- Scroll through existing workspaces
hl.bind(
	mainMod .. " + " .. "mouse_down",
	hl.dsp.focus({ workspace = "e+1" }),
	{ description = "[Workspaces|Navigation] next workspace" }
)
hl.bind(
	mainMod .. " + " .. "mouse_up",
	hl.dsp.focus({ workspace = "e-1" }),
	{ description = "[Workspaces|Navigation] previous workspace" }
)
-- Move/Switch to special workspace (scratchpad)
hl.bind(
	mainMod .. " + SHIFT" .. " + " .. "S",
	hl.dsp.window.move({ workspace = "special" }),
	{ description = "[Workspaces|Navigation|Special workspace] move to scratchpad" }
)
hl.bind(
	mainMod .. " + ALT" .. " + " .. "S",
	hl.dsp.window.move({ workspace = "special" }, { follow = false }),
	{ description = "[Workspaces|Navigation|Special workspace] move to scratchpad (silent)" }
)
hl.bind(
	mainMod .. " + " .. "S",
	hl.dsp.workspace.toggle_special(nil),
	{ description = "[Workspaces|Navigation|Special workspace] toggle scratchpad" }
)
-- Move focused window to a workspace silently
hl.bind(
	mainMod .. " + ALT" .. " + " .. 1,
	hl.dsp.window.move({ workspace = 1 }, { follow = false }),
	{ description = "[Workspaces|Navigation|Move window silently] move to workspace 1 (silent)" }
)
hl.bind(
	mainMod .. " + ALT" .. " + " .. 2,
	hl.dsp.window.move({ workspace = 2 }, { follow = false }),
	{ description = "[Workspaces|Navigation|Move window silently] move to workspace 2 (silent)" }
)
hl.bind(
	mainMod .. " + ALT" .. " + " .. 3,
	hl.dsp.window.move({ workspace = 3 }, { follow = false }),
	{ description = "[Workspaces|Navigation|Move window silently] move to workspace 3 (silent)" }
)
hl.bind(
	mainMod .. " + ALT" .. " + " .. 4,
	hl.dsp.window.move({ workspace = 4 }, { follow = false }),
	{ description = "[Workspaces|Navigation|Move window silently] move to workspace 4 (silent)" }
)
hl.bind(
	mainMod .. " + ALT" .. " + " .. 5,
	hl.dsp.window.move({ workspace = 5 }, { follow = false }),
	{ description = "[Workspaces|Navigation|Move window silently] move to workspace 5 (silent)" }
)
hl.bind(
	mainMod .. " + ALT" .. " + " .. 6,
	hl.dsp.window.move({ workspace = 6 }, { follow = false }),
	{ description = "[Workspaces|Navigation|Move window silently] move to workspace 6 (silent)" }
)
hl.bind(
	mainMod .. " + ALT" .. " + " .. 7,
	hl.dsp.window.move({ workspace = 7 }, { follow = false }),
	{ description = "[Workspaces|Navigation|Move window silently] move to workspace 7 (silent)" }
)
hl.bind(
	mainMod .. " + ALT" .. " + " .. 8,
	hl.dsp.window.move({ workspace = 8 }, { follow = false }),
	{ description = "[Workspaces|Navigation|Move window silently] move to workspace 8 (silent)" }
)
hl.bind(
	mainMod .. " + ALT" .. " + " .. 9,
	hl.dsp.window.move({ workspace = 9 }, { follow = false }),
	{ description = "[Workspaces|Navigation|Move window silently] move to workspace 9 (silent)" }
)
hl.bind(
	mainMod .. " + ALT" .. " + " .. 0,
	hl.dsp.window.move({ workspace = 10 }, { follow = false }),
	{ description = "[Workspaces|Navigation|Move window silently] move to workspace 10 (silent)" }
)
