-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- █▀▄▀█ █▀█ █▄░█ █ ▀█▀ █▀█ █▀█ █▀

-- █░▀░█ █▄█ █░▀█ █ ░█░ █▄█ █▀▄ ▄█

-- Set your monitor configuration here

-- See https://wiki.hyprland.org/Configuring/Monitors/

-- For a sample file, please refer to https://github.com/prasanthrangan/hyprdots/blob/main/Configs/.config/hypr/monitors.t2

hl.monitor({
    output   = "DP-1",
    mode     = "2560x1440@200",
    position = "0x0",
    scale    = 1,
})
