-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- █░█ █▀ █▀▀ █▀█   █▀█ █▀█ █▀▀ █▀▀ █▀
-- █▄█ ▄█ ██▄ █▀▄   █▀▀ █▀▄ ██▄ █▀░ ▄█

-- Set your personal hyprland configuration here

-- See https://wiki.hyprland.org/Configuring for more information

-- // █ █▄░█ █▀█ █░█ ▀█▀
-- // █ █░▀█ █▀▀ █▄█ ░█░

--  Uncomment to enable // change to a preferred value

-- 🔗 See https://wiki.hyprland.org/Configuring/Variables/#input

hl.config({
	input = {
		-- kb_layout = us
		follow_mouse = 1,
		-- sensitivity = 0
		force_no_accel = 1,
		accel_profile = "flat",
		-- numlock_by_default = true
		-- 🔗 See https://wiki.hyprland.org/Configuring/Variables/#touchpad
		touchpad = {
			natural_scroll = false,
		},
		repeat_rate = 25,
		repeat_delay = 300,
	},
})

-- 🔗 See https://wiki .hyprland.org/Configuring/Variables/#gestures

hl.config({
	gestures = {
		--     workspace_swipe = true
		--     workspace_swipe_fingers = 3
	},
})

-- for window shallow similar to devour

hl.config({
	misc = {
		-- enable_swallow = true
		-- swallow_regex = (foot|kitty|allacritty|Alacritty|ghostty|Ghostty|org.wezfurlong.wezterm)
	},
})

-- Don't show update on first launch

hl.config({
	ecosystem = {
		no_update_news = true,
	},
})

hl.config({
	cursor = {
		no_hardware_cursors = false,
	},
})

hl.config({
	general = {
		gaps_in = 3,
		gaps_out = 8,
		col = {
			active_border = { colors = { "rgba(bb9af7ff)", "rgba(b4f9f8ff)" }, angle = 45 },
			inactive_border = { colors = { "rgba(565f89cc)", "rgba(9aa5cecc)" }, angle = 45 },
		},
	},
})

hl.env("HYPRCURSOR_THEME", "BreezeX-RosePine-Linux")

hl.env("HYPRCURSOR_SIZE", 24)

-- XWayland / X11 apps use the legacy Xcursor theme
hl.env("XCURSOR_THEME", "BreezeX-RosePine-Linux")

hl.env("XCURSOR_SIZE", 24)

-- Autostart
hl.on("hyprland.start", function()
	hl.exec_cmd('hyprctl setcursor "BreezeX-RosePine-Linux" 24')
	hl.exec_cmd("hyprpaper")
	hl.exec_cmd("wayvnc")
end)
