-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- █░█░█ █ █▄░█ █▀▄ █▀█ █░█░█   █▀█ █░█ █░░ █▀▀ █▀
-- ▀▄▀▄▀ █ █░▀█ █▄▀ █▄█ ▀▄▀▄▀   █▀▄ █▄█ █▄▄ ██▄ ▄█

-- See https://wiki.hyprland.org/Configuring/Window-Rules/

--? ------- WINDOWRULES_HYPRLAND_V_0_53 COMPATIBLE ----------------

--   This Config is compatible with windowrules changes in Hyprland v0.53+

--   Any future breaking changes disables this block and notifies the user to update.

--   User template files will be provided in $XDG_DATA_HOME/hyde/templates/hypr/windowrules.conf for manual update.

-- hyprlang if WINDOWRULES_HYPRLAND_V_0_53

-- idle_inhibit rules

hl.window_rule({
	name = "media_players_idle_inhibit",
	match = {
		class = "^(.*celluloid.*)$|^(.*mpv.*)$|^(.*vlc.*)$",
	},
	idle_inhibit = "fullscreen",
})

hl.window_rule({
	name = "spotify_idle_inhibit",
	match = {
		class = "^(.*[Ss]potify.*)$",
	},
	idle_inhibit = "fullscreen",
})

hl.window_rule({
	name = "browsers_idle_inhibit",
	match = {
		class = "^(.*LibreWolf.*)$|^(.*floorp.*)$|^(.*brave-browser.*)$|^(.*firefox.*)$|^(.*chromium.*)$|^(.*zen.*)$|^(.*vivaldi.*)$",
	},
	idle_inhibit = "fullscreen",
})

-- Picture-in-Picture

hl.window_rule({
	name = "picture_in_picture_tag",
	match = {
		title = "^([Pp]icture[-\\s]?[Ii]n[-\\s]?[Pp]icture)(.*)$",
	},
	tag = "+picture-in-picture",
})

hl.window_rule({
	name = "picture_in_picture_layout",
	match = {
		title = "^([Pp]icture[-\\s]?[Ii]n[-\\s]?[Pp]icture)(.*)$",
	},
	tag = "+hyde_picture_in_picture",
	float = true,
	keep_aspect_ratio = true,
	move = { "(monitor_w*0.73)", "(monitor_h*0.72)" },
	size = { "(monitor_w*0.25)", "(monitor_h*0.25)" },
	pin = true,
})

hl.window_rule({
	name = "firefox_opacity",
	match = {
		class = "^(firefox)$",
	},
	opacity = "1.00 override 0.90 override 1",
})

hl.window_rule({
	name = "brave_opacity",
	match = {
		class = "^(brave-browser)$",
	},
	opacity = "0.90 override 0.90 override 1",
})

hl.window_rule({
	name = "code_oss_opacity",
	match = {
		class = "^(code-oss)$",
	},
	opacity = "1.00 override 0.80 override 1",
})

hl.window_rule({
	name = "vscode_opacity",
	match = {
		class = "^([Cc]ode)$",
	},
	opacity = "0.80 override 0.80 override 1",
})

hl.window_rule({
	name = "vscode_url_handler_opacity",
	match = {
		class = "^(code-url-handler)$",
	},
	opacity = "0.80 override 0.80 override 1",
})

hl.window_rule({
	name = "vscode_insiders_url_handler_opacity",
	match = {
		class = "^(code-insiders-url-handler)$",
	},
	opacity = "0.80 override 0.80 override 1",
})

hl.window_rule({
	name = "kitty_opacity",
	match = {
		class = "^(kitty)$",
	},
	opacity = "1.00 override 0.90 override 1",
})

hl.window_rule({
	name = "dolphin_opacity",
	match = {
		class = "^(org.kde.dolphin)$",
	},
	opacity = "0.80 override 0.80 override 1",
})

hl.window_rule({
	name = "ark_opacity",
	match = {
		class = "^(org.kde.ark)$",
	},
	opacity = "0.80 override 0.80 override 1",
})

hl.window_rule({
	name = "nwg_look_opacity",
	match = {
		class = "^(nwg-look)$",
	},
	opacity = "0.80 override 0.80 override 1",
})

hl.window_rule({
	name = "qt5ct_opacity",
	match = {
		class = "^(qt5ct)$",
	},
	opacity = "0.80 override 0.80 override 1",
})

hl.window_rule({
	name = "qt6ct_opacity",
	match = {
		class = "^(qt6ct)$",
	},
	opacity = "0.80 override 0.80 override 1",
})

hl.window_rule({
	name = "kvantummanager_opacity",
	match = {
		class = "^(kvantummanager)$",
	},
	opacity = "0.80 override 0.80 override 1",
})

hl.window_rule({
	name = "pavucontrol_opacity",
	match = {
		class = "^(org.pulseaudio.pavucontrol)$",
	},
	opacity = "0.80 override 0.70 override 1",
})

hl.window_rule({
	name = "blueman_opacity",
	match = {
		class = "^(blueman-manager)$",
	},
	opacity = "0.80 override 0.70 override 1",
})

hl.window_rule({
	name = "nm_applet_opacity",
	match = {
		class = "^(nm-applet)$",
	},
	opacity = "0.80 override 0.70 override 1",
})

hl.window_rule({
	name = "nm_connection_editor_opacity",
	match = {
		class = "^(nm-connection-editor)$",
	},
	opacity = "0.80 override 0.70 override 1",
})

hl.window_rule({
	name = "polkit_kde_agent_opacity",
	match = {
		class = "^(org.kde.polkit-kde-authentication-agent-1)$",
	},
	opacity = "0.80 override 0.70 override 1",
})

hl.window_rule({
	name = "polkit_gnome_agent_opacity",
	match = {
		class = "^(polkit-gnome-authentication-agent-1)$",
	},
	opacity = "0.80 override 0.70 override 1",
})

hl.window_rule({
	name = "portal_gtk_opacity",
	match = {
		class = "^(org.freedesktop.impl.portal.desktop.gtk)$",
	},
	opacity = "0.80 override 0.70 override 1",
})

hl.window_rule({
	name = "portal_hyprland_opacity",
	match = {
		class = "^(org.freedesktop.impl.portal.desktop.hyprland)$",
	},
	opacity = "0.80 override 0.70 override 1",
})

hl.window_rule({
	name = "steam_opacity",
	match = {
		class = "^([Ss]team)$",
	},
	opacity = "1.00 override 0.90 override 1",
})

hl.window_rule({
	name = "steamwebhelper_opacity",
	match = {
		class = "^(steamwebhelper)$",
	},
	opacity = "0.70 override 0.70 override 1",
})

hl.window_rule({
	name = "spotify_opacity",
	match = {
		class = "^([Ss]potify)$",
	},
	opacity = "1.00 override 0.70 override 1",
})

hl.window_rule({
	name = "spotify_free_opacity",
	match = {
		initial_title = "^(Spotify Free)$",
	},
	opacity = "1.00 override 0.70 override 1",
})

hl.window_rule({
	name = "spotify_premium_opacity",
	match = {
		initial_title = "^(Spotify Premium)$",
	},
	opacity = "1.00 override 0.70 override 1",
})

hl.window_rule({
	name = "qbittorrent_opacity",
	match = {
		class = "^(org.qbittorrent.qBittorrent)$",
	},
	opacity = "1.00 override 0.70 override 1",
})

hl.window_rule({
	name = "clapper_opacity",
	match = {
		class = "^(com.github.rafostar.Clapper)$",
	},
	opacity = "0.90 0.90",
})

-- Clapper-Gtk

hl.window_rule({
	name = "flatseal_opacity",
	match = {
		class = "^(com.github.tchx84.Flatseal)$",
	},
	opacity = "0.80 0.80",
})

-- Flatseal-Gtk

hl.window_rule({
	name = "cartridges_opacity",
	match = {
		class = "^(hu.kramo.Cartridges)$",
	},
	opacity = "0.80 0.80",
})

-- Cartridges-Gtk

hl.window_rule({
	name = "obs_studio_opacity",
	match = {
		class = "^(com.obsproject.Studio)$",
	},
	opacity = "0.80 0.80",
})

-- Obs-Qt

hl.window_rule({
	name = "gnome_boxes_opacity",
	match = {
		class = "^(gnome-boxes)$",
	},
	opacity = "0.80 0.80",
})

-- Boxes-Gtk

hl.window_rule({
	name = "vesktop_opacity",
	match = {
		class = "^(vesktop)$",
	},
	opacity = "1.00 0.80",
})

-- Vesktop

hl.window_rule({
	name = "discord_opacity",
	match = {
		class = "^(discord)$",
	},
	opacity = "0.80 0.80",
})

-- Discord-Electron

hl.window_rule({
	name = "webcord_opacity",
	match = {
		class = "^(WebCord)$",
	},
	opacity = "0.80 0.80",
})

-- WebCord-Electron

hl.window_rule({
	name = "armcord_opacity",
	match = {
		class = "^(ArmCord)$",
	},
	opacity = "0.80 0.80",
})

-- ArmCord-Electron

hl.window_rule({
	name = "warp_opacity",
	match = {
		class = "^(app.drey.Warp)$",
	},
	opacity = "0.80 0.80",
})

-- Warp-Gtk

hl.window_rule({
	name = "protonup_qt_opacity",
	match = {
		class = "^(net.davidotek.pupgui2)$",
	},
	opacity = "0.80 0.80",
})

-- ProtonUp-Qt

hl.window_rule({
	name = "protontricks_opacity",
	match = {
		class = "^(yad)$",
	},
	opacity = "0.80 0.80",
})

-- Protontricks-Gtk

hl.window_rule({
	name = "signal_opacity",
	match = {
		class = "^(Signal)$",
	},
	opacity = "0.80 0.80",
})

-- Signal-Gtk

hl.window_rule({
	name = "planify_opacity",
	match = {
		class = "^(io.github.alainm23.planify)$",
	},
	opacity = "0.80 0.80",
})

-- planify-Gtk

hl.window_rule({
	name = "upscaler_opacity",
	match = {
		class = "^(io.gitlab.theevilskeleton.Upscaler)$",
	},
	opacity = "0.80 0.80",
})

-- Upscaler-Gtk

hl.window_rule({
	name = "video_downloader_opacity",
	match = {
		class = "^(com.github.unrud.VideoDownloader)$",
	},
	opacity = "0.80 0.80",
})

-- VideoDownloader-Gtk

hl.window_rule({
	name = "impression_opacity",
	match = {
		class = "^(io.gitlab.adhami3310.Impression)$",
	},
	opacity = "0.80 0.80",
})

-- Impression-Gtk

hl.window_rule({
	name = "missioncenter_opacity",
	match = {
		class = "^(io.missioncenter.MissionCenter)$",
	},
	opacity = "0.80 0.80",
})

-- MissionCenter-Gtk

hl.window_rule({
	name = "warehouse_opacity",
	match = {
		class = "^(io.github.flattool.Warehouse)$",
	},
	opacity = "0.80 0.80",
})

-- Warehouse-Gtk

hl.window_rule({
	name = "signal_float",
	match = {
		class = "^(Signal)$",
	},
	float = true,
})

-- Signal-Gtk

hl.window_rule({
	name = "clapper_float",
	match = {
		class = "^(com.github.rafostar.Clapper)$",
	},
	float = true,
})

-- Clapper-Gtk

hl.window_rule({
	name = "warp_float",
	match = {
		class = "^(app.drey.Warp)$",
	},
	float = true,
})

-- Warp-Gtk

hl.window_rule({
	name = "protonup_qt_float",
	match = {
		class = "^(net.davidotek.pupgui2)$",
	},
	float = true,
})

-- ProtonUp-Qt

hl.window_rule({
	name = "protontricks_float",
	match = {
		class = "^(yad)$",
	},
	float = true,
})

-- Protontricks-Gtk

hl.window_rule({
	name = "image_viewer_float",
	match = {
		class = "^(eog)$",
	},
	float = true,
})

-- Imageviewer-Gtk

hl.window_rule({
	name = "planify_float",
	match = {
		class = "^(io.github.alainm23.planify)$",
	},
	float = true,
})

-- planify-Gtk

hl.window_rule({
	name = "upscaler_float",
	match = {
		class = "^(io.gitlab.theevilskeleton.Upscaler)$",
	},
	float = true,
})

-- Upscaler-Gtk

hl.window_rule({
	name = "video_downloader_float",
	match = {
		class = "^(com.github.unrud.VideoDownloader)$",
	},
	float = true,
})

-- VideoDownloader-Gkk

hl.window_rule({
	name = "impression_float",
	match = {
		class = "^(io.gitlab.adhami3310.Impression)$",
	},
	float = true,
})

-- Impression-Gtk

hl.window_rule({
	name = "missioncenter_float",
	match = {
		class = "^(io.missioncenter.MissionCenter)$",
	},
	float = true,
})

-- MissionCenter-Gtk

hl.window_rule({
	name = "hypremoji_float",
	match = {
		title = "^(HyprEmoji)$",
	},
	float = true,
})

hl.window_rule({
	name = "hypremoji_position",
	match = {
		title = "^(HyprEmoji)$",
	},
	move = "(cursor_x-(window_w*0.5)) (cursor_y-(window_h*0.05))",
})

-- workaround for jetbrains IDEs dropdowns/popups cause flickering

hl.window_rule({
	name = "jetbrains_popup_no_initial_focus",
	match = {
		class = "^(.*jetbrains.*)$",
		title = "^(win[0-9]+)$",
	},
	no_initial_focus = true,
})

hl.window_rule({
	name = "signal_workspace",
	match = { class = "^(signal)$" },
	workspace = "4 silent",
})

hl.window_rule({
	name = "zapzap_workspace",
	match = { class = "^(com.rtosta.zapzap)$" },
	workspace = "4 silent",
})

hl.window_rule({
	name = "android_messages_workspace",
	match = { class = "^(pw.kmr.amd)$" },
	workspace = "4 silent",
})

hl.window_rule({
	name = "betterbird_workspace",
	match = { class = "^(eu.betterbird.Betterbird)$" },
	workspace = "5 silent",
})

hl.window_rule({
	name = "spotify_workspace",
	match = { class = "^([Ss]potify)$" },
	workspace = "6 silent",
})

hl.window_rule({
	name = "steam_workspace",
	match = { class = "^([Ss]team)$" },
	workspace = "7 silent",
})

hl.window_rule({
	name = "heroic_workspace",
	match = { class = "^([Hh]eroic)$" },
	workspace = "7 silent",
})

-- █░░ ▄▀█ █▄█ █▀▀ █▀█   █▀█ █░█ █░░ █▀▀ █▀

-- █▄▄ █▀█ ░█░ ██▄ █▀▄   █▀▄ █▄█ █▄▄ ██▄ ▄█

hl.layer_rule({
	match = {
		namespace = "rofi",
	},
	blur = true,
})

hl.layer_rule({
	match = {
		namespace = "rofi",
	},
	ignore_alpha = 0,
})

hl.layer_rule({
	match = {
		namespace = "notifications",
	},
	blur = true,
})

hl.layer_rule({
	match = {
		namespace = "notifications",
	},
	ignore_alpha = 0,
})

hl.layer_rule({
	match = {
		namespace = "swaync-notification-window",
	},
	blur = true,
})

hl.layer_rule({
	match = {
		namespace = "swaync-notification-window",
	},
	ignore_alpha = 0,
})

hl.layer_rule({
	match = {
		namespace = "swaync-control-center",
	},
	blur = true,
})

hl.layer_rule({
	match = {
		namespace = "swaync-control-center",
	},
	ignore_alpha = 0,
})

hl.layer_rule({
	match = {
		namespace = "logout_dialog",
	},
	blur = true,
})

-- hyprlang endif
